sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
env:
  - VERSION=1.0.0-SNAPSHOT ARCHETYPE_VERSION=5.2.0-SNAPSHOT GFW_BRANCH=master ARCHETYPE_BRANCH=master TARGET_PROJECT=target-project
  - VERSION=1.0.0-SNAPSHOT ARCHETYPE_VERSION=5.1.1-SNAPSHOT GFW_BRANCH=5.1.x ARCHETYPE_BRANCH=5.1.x TARGET_PROJECT=target-project
  - VERSION=1.0.0-SNAPSHOT ARCHETYPE_VERSION=5.1.0.RELEASE GFW_BRANCH=5.1.0.RELEASE ARCHETYPE_BRANCH=5.1.0.RELEASE TARGET_PROJECT=target-project
  - TOMCAT8_VERSION="8.0.29"

install:
  - echo "==================== install terasoluna-gfw ===================="
  - pushd `pwd`
  - cd $HOME/build
  - if [[ -z $GFW_BRANCH ]]; then GFW_BRANCH=master; fi
  - git clone --depth=1 --branch=$GFW_BRANCH https://github.com/terasolunaorg/terasoluna-gfw.git terasolunaorg/terasoluna-gfw
  - cd terasolunaorg/terasoluna-gfw
  - bash ./mvn-build-all.sh install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -Dsource.skip=true
  - popd
  - echo "==================== install terasoluna-gfw-web-multi-blank (None) ===================="
  - if [[ -z $ARCHETYPE_BRANCH ]]; then ARCHETYPE_BRANCH=master; fi
  - pushd `pwd`
  - cd $HOME/build
  - git clone --depth=1 --branch=$ARCHETYPE_BRANCH https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank.git terasolunaorg/terasoluna-gfw-web-multi-blank
  - pushd `pwd`
  - cd terasolunaorg/terasoluna-gfw-web-multi-blank
  - sed -i -e "s/deploy/install/g" create-maven-archetype.sh
  - bash create-maven-archetype.sh
  - popd
  - rm -rf terasolunaorg/terasoluna-gfw-web-multi-blank
  - popd
  - echo "==================== install terasoluna-gfw-web-multi-blank (JPA) ===================="
  - pushd `pwd`
  - cd $HOME/build
  - git clone --depth=1 --branch=$ARCHETYPE_BRANCH https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank.git terasolunaorg/terasoluna-gfw-web-multi-blank
  - pushd `pwd`
  - cd terasolunaorg/terasoluna-gfw-web-multi-blank
  - sed -i -e "s/deploy/install/g" create-maven-archetype.sh
  - sed -i -e "s/^sh /bash /g" create-maven-archetype-jpa.sh
  - bash create-maven-archetype-jpa.sh
  - popd
  - rm -rf terasolunaorg/terasoluna-gfw-web-multi-blank
  - popd
  - echo "==================== install terasoluna-gfw-web-multi-blank (MyBatis3) ===================="
  - pushd `pwd`
  - cd $HOME/build
  - git clone --depth=1 --branch=$ARCHETYPE_BRANCH https://github.com/terasolunaorg/terasoluna-gfw-web-multi-blank.git terasolunaorg/terasoluna-gfw-web-multi-blank
  - pushd `pwd`
  - cd terasolunaorg/terasoluna-gfw-web-multi-blank
  - sed -i -e "s/deploy/install/g" create-maven-archetype.sh
  - sed -i -e "s/^sh /bash /g" create-maven-archetype-mybatis3.sh
  - bash create-maven-archetype-mybatis3.sh
  - popd
  - rm -rf terasolunaorg/terasoluna-gfw-web-multi-blank
  - popd
  - echo "==================== install terasoluna-gfw-web-blank (None) ===================="
  - pushd `pwd`
  - cd $HOME/build
  - git clone --depth=1 --branch=$ARCHETYPE_BRANCH https://github.com/terasolunaorg/terasoluna-gfw-web-blank.git terasolunaorg/terasoluna-gfw-web-blank
  - pushd `pwd`
  - cd terasolunaorg/terasoluna-gfw-web-blank
  - sed -i -e "s/deploy/install/g" create-maven-archetype.sh
  - bash create-maven-archetype.sh
  - popd
  - rm -rf terasolunaorg/terasoluna-gfw-web-blank
  - popd
  - echo "==================== install terasoluna-gfw-web-blank (JPA) ===================="
  - pushd `pwd`
  - cd $HOME/build
  - git clone --depth=1 --branch=$ARCHETYPE_BRANCH https://github.com/terasolunaorg/terasoluna-gfw-web-blank.git terasolunaorg/terasoluna-gfw-web-blank
  - pushd `pwd`
  - cd terasolunaorg/terasoluna-gfw-web-blank
  - sed -i -e "s/deploy/install/g" create-maven-archetype.sh
  - sed -i -e "s/^sh /bash /g" create-maven-archetype-jpa.sh
  - bash create-maven-archetype-jpa.sh
  - popd
  - rm -rf terasolunaorg/terasoluna-gfw-web-blank
  - popd
  - echo "==================== install terasoluna-gfw-web-blank (MyBatis3) ===================="
  - pushd `pwd`
  - cd $HOME/build
  - git clone --depth=1 --branch=$ARCHETYPE_BRANCH https://github.com/terasolunaorg/terasoluna-gfw-web-blank.git terasolunaorg/terasoluna-gfw-web-blank
  - pushd `pwd`
  - cd terasolunaorg/terasoluna-gfw-web-blank
  - sed -i -e "s/deploy/install/g" create-maven-archetype.sh
  - sed -i -e "s/^sh /bash /g" create-maven-archetype-mybatis3.sh
  - bash create-maven-archetype-mybatis3.sh
  - popd
  - rm -rf terasolunaorg/terasoluna-gfw-web-blank
  - popd

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CARGO_DAEMON_WEBAPP_VERSION=1.4.19
  - mvn dependency:copy -Dartifact=org.codehaus.cargo:cargo-daemon-webapp:${CARGO_DAEMON_WEBAPP_VERSION}:war -DoutputDirectory=./ -Dorg.codehaus.cargo.cargo-maven2-plugin.version=${CARGO_DAEMON_WEBAPP_VERSION} -Dcargo.daemon.url=http://localhost:8080 -Dcargo.maven.containerId=tomcat8x -Dcargo.maven.containerUrl=http://archive.apache.org/dist/tomcat/tomcat-8/v${TOMCAT8_VERSION}/bin/apache-tomcat-${TOMCAT8_VERSION}.zip
  - java -jar ./target/cargo-daemon-webapp-${CARGO_DAEMON_WEBAPP_VERSION}.war &

script: 
  - echo "==================== Generate Tutorial Apps ===================="
  - |
    for FILE in `find ./*/scripts/create-app.sh -maxdepth 1`; do
      echo "execute $FILE"
      bash $FILE
      buildResult=$?
      if test ${buildResult} -ne 0 ; then
        echo "[ERROR] Failed a build."
        exit ${buildResult}
      fi
    done
  - echo "==================== Make war files ===================="
  - |
    for POM in `find ./$TARGET_PROJECT/*/pom.xml -maxdepth 1`; do
      echo"make $POM warfile"
      mvn -U -f $POM package -DskipTests=true
      buildResult=$?
      if test ${buildResult} -ne 0 ; then
        echo "[ERROR] Failed a build."
        exit ${buildResult}
      fi
    done
  - echo "==================== Build Tutorial Apps without Tests ===================="
  - |
    for POM in `find ./$TARGET_PROJECT/*/pom.xml -maxdepth 1`; do
      echo "build $POM"
      mvn -U -f $POM install -DskipTests=true
      buildResult=$?
      if test ${buildResult} -ne 0 ; then
        echo "[ERROR] Failed a build."
        exit ${buildResult}
      fi
    done
  - echo "==================== Run AP And Test Tutorial Apps (e2e test) ===================="
  - |
    for WEBAPPOM in `find ./$TARGET_PROJECT/*/*-web/pom.xml -maxdepth 1`;do
      echo "Run $WEBAPPOM"
      mvn clean verify org.codehaus.cargo:cargo-maven2-plugin:daemon-start -f $WEBAPPOM
      buildResult=$?
      if test ${buildResult} -ne 0 ; then
        echo "[ERROR] Failed a build."
        exit ${buildResult}
      fi
      SELENIUMPOM="${WEBAPPOM%-web/pom.xml}-selenium/pom.xml"
      echo "Test $SELENIUMPOM"
      mvn test -f $SELENIUMPOM
      buildResult=$?
      if test ${buildResult} -ne 0 ; then
        echo "[ERROR] Failed a build."
        exit ${buildResult}
      fi
    done
